export const techIcons: Record<string, string> = {
  TypeScript: "simple-icons:typescript",
  JavaScript: "simple-icons:javascript",
  Python: "simple-icons:python",
  MySQL: "simple-icons:mysql",
  LaTeX: "simple-icons:latex",
  C: "simple-icons:c",
  HTML: "simple-icons:html5",
  CSS: "simple-icons:css3",
  Markdown: "simple-icons:markdown",

  Astro: "simple-icons:astro",
  React: "simple-icons:react",
  "Node.js": "simple-icons:nodedotjs",
  ExpressJS: "simple-icons:express",
  TailwindCSS: "simple-icons:tailwindcss",
  NextJS: "simple-icons:nextdotjs",
  Ros2: "simple-icons:ros",

  Streamlit: "simple-icons:streamlit",
  Pandas: "simple-icons:pandas",
  NumPy: "simple-icons:numpy",
  ScikitLearn: "simple-icons:scikitlearn",
  PyTorch: "simple-icons:pytorch",
  YOLO: "simple-icons:yolo",
  OpenCV: "simple-icons:opencv",

  Conda: "simple-icons:anaconda",
  GitHub: "simple-icons:github",
  Docker: "simple-icons:docker",
  Kaggle: "simple-icons:kaggle",
  Jupyter: "simple-icons:jupyter",
  "VS Code": "simple-icons:visualstudiocode",
  Git: "simple-icons:git",
  "Google Cloud": "simple-icons:googlecloud",
  Linux: "simple-icons:ubuntu",
  Vercel: "simple-icons:vercel",
  "Postman API": "simple-icons:postman",
  "Google Looker Studio": "simple-icons:looker",

  // PostgreSQL: "simple-icons:postgresql",
  MongoDB: "simple-icons:mongodb",
  Redis: "simple-icons:redis",
  Prisma: "simple-icons:prisma",
  "Google BigQuery": "simple-icons:googlebigquery",

  AutoCad: "simple-icons:autocad",
  "Microsoft Office Suite": "simple-icons:microsoftoffice",
  "Google Workspace": "simple-icons:google",
  "Adobe Illustrator": "simple-icons:adobeillustrator",
  "Adobe Photoshop": "simple-icons:adobephotoshop",
  Blender: "simple-icons:blender",

  Website: "mdi:web",
  Email: "mdi:email",
  LinkedIn: "simple-icons:linkedin",
  Instagram: "simple-icons:instagram",
};
